### PR TITLE
Hello world fork fix

### PR DESCRIPTION
**Pull request by mikarinneoracle**
A fix to this: https://github.com/oracle/cloud-native-devops-workshop/issues/42

### CODE REVIEW

**Comment by brunoborges** [comment]
@mikarinneoracle, can you please consider moving the hello-world app to this repository?

**Comment by mikarinneoracle** [comment]
@brunoborges That's a good point, let me check that. Thanks!

**Comment by mikarinneoracle** [comment]
@brunoborges Would it be ok to do that change in the next iteration ?

**Comment by brunoborges** [comment]
Sure thing

**Review by mikeraab — APPROVED** [review]

**Comment by mikarinneoracle** [comment]
@brunoborges Any chance to merge ? Copied changes from the other pull request and closed that one. Thanks

**Review by brunoborges — APPROVED** [review]

**Pull request merged**
