### PR TITLE
Blackjack HOL Lab

### PR DESCRIPTION
**Pull request by peterfz**
Blackjack HOL lab files and instructions

### CODE REVIEW

**Comment by peterfz** [comment]
Bruno please pull

**Comment by MaciejGruszka** [comment]
You added ZIP and PDF. I think This is not acceptable. PDF is having watermark "Oracle Internal and Academy Use Only" We cant have it here. Any tutorial needs to be prepared as MD document with images in png format in this repo. Also ZIP file is not a right thing to place. You should add it in an open format and provide scripts for packing (as part of your tutorial). Otherwise on github it is impossible to look for differences between versions. Bruno WDYT?

**Comment by peterfz** [comment]
Hi Maciej,I agree with what you are saying but at that's a learning curve for the creator OU. Bruno, what we need is a document repository. If these conversions need to happen for GitHub we will need additional time once OU have finalized their doc.

**Comment by brunoborges** [comment]
@peterfz, we need it to be Markdown, and the ZIP file must be extracted/expanded within the GitHub repository, and instructions must be appropriate.

**Comment by peterfz** [comment]
Okay, will work on that.We'll need to provide additional instructions in a Readme.md file

**Pull request closed without merging**
